server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/prontmed
    username: root
    password: 84219019
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: prontmed
  mvc:
    throw-exception-if-no-handler-found: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
